# Generated by Django 4.1.5 on 2023-04-19 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConpletionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='HouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=45)),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(max_length=45)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.IntegerField()),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.orderstatus')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.paymentstatus')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('conpletion_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.conpletionstatus')),
                ('images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.houseimages')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.houselocation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.housetypes')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('paid', models.IntegerField(blank=True, null=True)),
                ('house_price', models.IntegerField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.house')),
                ('pay_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.paymentstatus')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.paymenttype')),
            ],
        ),
    ]
