# Generated by Django 4.1.5 on 2023-04-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_house_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='house',
            name='images',
        ),
        migrations.AddField(
            model_name='houseimages',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.house'),
        ),
    ]
