# Generated by Django 4.1.5 on 2023-04-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_houseimages_house_house_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='images',
        ),
        migrations.RemoveField(
            model_name='houseimages',
            name='for_house',
        ),
        migrations.AddField(
            model_name='houseimages',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.house'),
        ),
    ]
