# Generated by Django 4.1.5 on 2023-04-24 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_house_images_remove_houseimages_for_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimages',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.house'),
        ),
    ]
